[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-solver"
version = "2.3.0"
description = "MCP server for constraint solving"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.2.0",
    "minizinc",
    "tomli;python_version<'3.11'",
    "z3-solver>=4.12.1",
    "python-sat",
    "six"
]

[project.scripts]
mcp-solver = "mcp_solver.server:main"
test-setup = "mcp_solver.test_setup:main"

[project.optional-dependencies]
dev = [
    "coverage",
    "pytest",
]

[tool.black]
line-length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true

# Override default memo file location by uncommenting and modifying one of these:

# Windows: %APPDATA%\mcp-solver\memo.md
#memo_file = "%APPDATA%\\mcp-solver\\memo.md"

# macOS: ~/Library/Application Support/mcp-solver/memo.md
#memo_file = "~/Library/Application Support/mcp-solver/memo.md"

# Linux: ~/.config/mcp-solver/memo.md
#memo_file = "~/.config/mcp-solver/memo.md"