[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-solver"
version = "2.3.0"
description = "MCP server for constraint solving"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.2.0",
    "minizinc",
    "tomli",
    "six"
]

[project.optional-dependencies]
z3 = [
    "z3-solver>=4.12.1",
]
pysat = [
    "python-sat",
]
client = [
    "langchain>=0.3.18",
    "langchain-core>=0.2.22",
    "langchain-mcp-adapters>=0.0.2",
    "langgraph>=0.2.74",
    "langchain-openai>=0.3.5",
    "langchain-anthropic>=0.3.7",
    "langchain-google-genai>=2.0.9",
    "google-generativeai>=0.7.0",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "rich>=13.9.4",
    "uuid>=1.30",
]
all = [
    "mcp-solver[z3,pysat,client]",
]
dev = [
    "coverage",
    "pytest",
]

[project.scripts]
test-setup = "mcp_solver.mzn.test_setup:main"
test-setup-z3 = "mcp_solver.z3.test_setup:main"
test-setup-pysat = "mcp_solver.pysat.test_setup:main"
test-setup-client = "mcp_solver.client.test_setup:main"
mcp-solver = "mcp_solver.__main__:main"
mcp-solver-mzn = "mcp_solver.__main__:main_mzn"
mcp-solver-z3 = "mcp_solver.__main__:main_z3"
mcp-solver-pysat = "mcp_solver.__main__:main_pysat"
test-client = "mcp_solver.client.client:main_cli"
test-client-mzn = "mcp_solver.client.test_client_mzn:main"
test-client-pysat = "mcp_solver.client.test_client_pysat:main"
test-client-z3 = "mcp_solver.client.test_client_z3:main"

[tool.black]
line-length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true

# Override default memo file location by uncommenting and modifying one of these:

# Windows: %APPDATA%\mcp-solver\memo.md
#memo_file = "%APPDATA%\\mcp-solver\\memo.md"

# macOS: ~/Library/Application Support/mcp-solver/memo.md
#memo_file = "~/Library/Application Support/mcp-solver/memo.md"

# Linux: ~/.config/mcp-solver/memo.md
#memo_file = "~/.config/mcp-solver/memo.md"